/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  snishi
 * Created: 4/03/2023
 */

-- Create base ticket data
 
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET A' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET B' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET C' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET D' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET E' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET F' );
