-- liquibase formatted sql

-- changeset liquibase:2
 
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET A' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET B' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET C' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET D' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET E' );
INSERT INTO TICKETS (CREATION_DTTM, TEXT) VALUES (CURRENT_TIMESTAMP, 'TICKET F' );